### ISSUE TITLE
Roleplay XP System

### ISSUE THREAD

**Issue by zunath** [zunath/NWN.FinalFantasy#12]
Add a system which rewards players for roleplaying. They should receive XP periodically as long as they're engaged in roleplay.

Refer to SWLOR for a system that should be ready out-of-the-box.

**Comment by taelon875** [comment]
Cormyr has a system where you get a set amount of levels you can get without RPXP but then after that a portion has to come from RP. I think it is a good system and we could consider it as well. It stops people from just grinding and could work well. They limit how much RPXP can receive a day though, which I am not sure how a stand, but it might be worth considering if we have a questing system with daily things like with SWLOR's guild quests.
